# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userbringitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='friendly_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='goes_to', through='app.Inscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
