# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170403_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='items',
            field=models.ManyToManyField(to='app.Item'),
        ),
    ]
