# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 07:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170404_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['admin__username', 'datetime__month']),
        ),
    ]
