# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 20:28
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170404_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['admin__username', 'date_time__month']),
        ),
    ]
