# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170413_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbringitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='app.Item'),
        ),
    ]
