# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170503_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbringitem',
            name='qty',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
