# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170509_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='emoji',
            new_name='name',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='emoji_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
